### ISSUE TITLE
Encrypted String Can't Decrypt on Rave server

### ISSUE THREAD

**Issue by skyusuf15** [TadeSamson/RavePaymentDataEncryption#1]
Hi, i downloaded and run this project  which i use to get an encrypted string, i query rave api using Advanced REST Client (ARC). i got an error message with a decypt result "{'data':'tade'}" , i got this error message because the result is not the right parameters the api is expecting so i tried to implement this on my project, but instead i got error messages when i queried. i also retry your RavePaymentDataEncryption and it fails too, here is a screenshot below
![screenshot 49](https://user-images.githubusercontent.com/16038049/27474036-f9bd348a-57f8-11e7-95ae-02e712bf4a5a.png)
![screenshot 50](https://user-images.githubusercontent.com/16038049/27474045-fd5eafd8-57f8-11e7-9cf1-0fff377fdbe1.png)

Am thinking this issue is from  rave server because for it to have decrypt once then something is wrong somewhere

**Comment by tadesamson** [comment]
wow! this issue has been opened since june 23? That's so bad. 
Okay, to the problem. I see you're sending the encrypted sample payload {"data":"tade"} to rave endpoint. the issue is rave doesn't recognise anything like that and I used that only for sample purpose on how to consume the rave api.. on rave website, the payload data looks like this

```
 {
  "PBFPubKey": "FLWPUBK-7adb6177bd71dd43c2efa3f1229e3b7f-X",
  "accountnumber": "0690000007",
  "currency": "NGN",
  "country": "NG",
  "accountbank": "044", // to get a list of banks and associated bank codes, visit [https://www.flutterwave.com/documentation/banks-enquiry/]
  "amount": "300",
  "email": "tester@flutter.co",
  "firstname": "temi",
  "lastname": "desola",
  "IP": "40.17.80.1",
  "txRef": "MC-7663-MG",
  "narration": "FLW-ACCTRANSFER",
  "device_fingerprint": "69e6b7f0b72037aa8428b70fbe03986c"
}
```

this is what you need to encrypt not my sample json data here then send the encrypted string as client parameter just as you've done above. that way, you'll get the right response from rave.

for example, see the encrypted payload generated below

![2017-09-12_03h00_55](https://user-images.githubusercontent.com/10289859/30304724-d1cbbd9c-9723-11e7-9a49-d8817bd11831.png)


copying this cipher to maybe postman and triggering the rave request brings a successful response

![2017-09-12_03h02_59](https://user-images.githubusercontent.com/10289859/30304778-0ba0a1a4-9724-11e7-8759-6162c4c2bed5.png)

I'll update the description section to assist in easy usage. sorry about the misuse of this nugget.
